### ISSUE TITLE
Allow anyone to label these issues

### ISSUE THREAD

**Issue by jensimmons** [web-platform-tests/interop-2022#10]
It seems permissions are locked down. I'm not able to appropriately label issues as a `proposal`, or assign an issue, etc. /@jgraham or @foolip

**Comment by jgraham** [comment]
I've added the "triage" role to the wpt reviewers group, which is anyone who's been involved with wpt, and invited you. Does that sufficiently fix the problem?

**Comment by jensimmons** [comment]
That's fine. 

Could someone with privileges then label "Box Alignment on Block Boxes" and "Cascade Layers" as proposals.
