### ISSUE TITLE
Remove/Change containment tests testing support for display: ruby-text

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop-2022#101]
** Test List **

* css/css-contain/contain-layout-017.html
* css/css-contain/contain-paint-021.html

** Rationale **

Both Chrome & Safari don't support CSS display values for ruby. It doesn't seem reasonable to test this in the context of containment.

**Comment by nt1m** [comment]
The other possibility is to change the tests to use `<rt>`.

**Comment by foolip** [comment]
Both of these tests were added here: https://github.com/web-platform-tests/wpt/pull/12269

@mrego do you have any input here?

Here are the results on wpt.fyi:
https://wpt.fyi/results/css/css-contain/contain-layout-017.html?label=experimental&label=master&aligned
https://wpt.fyi/results/css/css-contain/contain-paint-021.html?label=experimental&label=master&aligned

The Chromium bug for both failures is https://bugs.chromium.org/p/chromium/issues/detail?id=880802.

I think the question here is this is testing anything using `display: ruby-text` that isn't also tested in some other way? If so, it might make sense to add new tests that expose the same bugs without relying on `display: ruby-text`, and swap out the tests included in Interop 2022.

**Comment by foolip** [comment]
@lilles do you know who might be able to look at this from the Chromium side?

Also ping @jgraham for finding a Gecko contact.

**Comment by nt1m** [comment]
@foolip It's being changed here to use `<rt>/<ruby>` instead: https://github.com/web-platform-tests/wpt/pull/35338

The test is specifically testing that internal ruby boxes aren't affected by layout/paint containment, while display: ruby-text triggers one, <rt> also does.

**Comment by lilles** [comment]
> @lilles do you know who might be able to look at this from the Chromium side?

@tkent-google has been working on ruby in Chromium

**Comment by nt1m** [comment]
Fixed by https://github.com/web-platform-tests/wpt/pull/35338 . I think we can consider this issue done.
