### ISSUE TITLE
Remove relative color syntax from Interop 2022

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop-2022#104]
** Test List **

* css/css-color/parsing/relative-color-computed.html
* css/css-color/parsing/relative-color-invalid.html
* css/css-color/parsing/relative-color-valid.html

** Rationale **

CSSWG has not mentioned relative color syntax is ready to ship (@emilio had concerns with the syntax) unlike color-mix() or gradient color space interpolation, and only WebKit has a working implementation. At this stage of the year, we feel like spec work is not appropriate.

See https://github.com/w3c/csswg-drafts/issues/7310#issuecomment-1156717607

**Comment by nt1m** [comment]
@foolip Can you please add this to tomorrow's agenda?

**Comment by jgraham** [comment]
@emilio Do you agree with the proposal to remove these tests?

**Comment by foolip** [comment]
@una @argyleink @sesse can any of you help judge if dropping these tests makes sense for Chromium?

**Comment by emilio** [comment]
Yes, removing these for now would be great.

**Comment by foolip** [comment]
Here are the test results for ease of review:
https://wpt.fyi/results/css/css-color/parsing?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2022-color%20relative

**Comment by foolip** [comment]
I prepared https://github.com/web-platform-tests/wpt-metadata/pull/2938 to see what it'd look like.

**Comment by argyleink** [comment]
I think it's fair to assess relative color syntax as not likely to ship in 2022

**Comment by nt1m** [comment]
@foolip Is this safe to assume there's consensus to remove the tests?

Fwiw, WebKit also has a [PR to enable relative color syntax](https://github.com/WebKit/WebKit/pull/2621) (which would make all those tests pass), but given the lack of signals from CSSWG, my position is to remove them from 2022 for now.

**Comment by svgeesus** [comment]
Pinging @leaverou who is the CSS Color 5 editor who did most of the Relative Color Syntax spec work.

**Comment by LeaVerou** [comment]
I think it makes sense to prioritize `color-mix()` or gradient interpolation over RCS.

**Comment by svgeesus** [comment]
> @emilio had concerns with the syntax

I see [zero open issues on RCS](https://github.com/w3c/csswg-drafts/labels/css-color-5). @emilio could you open one, so we know what your issue was? If it was mentioned in passing in another issue feel free to link to that.

**Comment by jensimmons** [comment]
> I think it makes sense to prioritize color-mix(), wide gamut colors, and gradient interpolation over RCS, yes.

This is not the issue at hand. There is no "prioritization" involved here. 

The CSSWG resolved that several color related features have standards that are complete, and so the features can be shipped.

Relative color syntax was not on that list because it was deemed not ready. The recommendation was that browsers should not ship relative color syntax. 

Because of this fact, these tests should not be part of the Interop 2022 score. Interop only scores things that are fully standardized and shippable. 

If you believe the spec is ready, Lea, and browsers should ship, then please raise the issue at the CSSWG to change the past resolution. With such a resolution, this can remain in Interop 2022. 

If there is work to be done, please ensure it is done, so browses can ship later, and these tests can be removed for now, and added to Interop 2023 later. 

This issue is not the place to debate whether or not relative color syntax is shippable. Please do that work in the CCSWG. 

This issue is to clarify whether or not existing WPT for relative color syntax should be included in Interop 2022.

**Comment by LeaVerou** [comment]
> If you believe the spec is ready, Lea, and browsers should ship, then please raise the issue at the CSSWG to change the past resolution. With such a resolution, this can remain in Interop 2022.

There is no resolution to change, because there is no resolution that RCS is _not_ ready to ship. For your reference, the two actual resolutions from that discussion are [here](https://github.com/w3c/csswg-drafts/issues/7310#issuecomment-1156717607).

**Comment by nt1m** [comment]
Quoting from https://github.com/w3c/csswg-drafts/issues/7310#issuecomment-1156717607 :

> <fantasai> emilio: about relative color syntax, less enthusiastic because only one implementation
> <fantasai> emilio: and their implementation seems to have same interop concerns as color-mix() where we had differences between WebKit / gecko
> <fantasai> emilio: so not so sure about it ready to ship
> <emilio> fantasai: happy with emilio's proposal to resolve on color-mix() + gradients but not yet on relative colors

There was a resolution, just buried in the conversation. Anyway, I do think it's a bit late at this point in the year to be wondering these kinds of questions for Interop, though I'll let the Chrome team make the final call.

**Comment by emilio** [comment]
> > @emilio had concerns with the syntax
> 
> I see [zero open issues on RCS](https://github.com/w3c/csswg-drafts/labels/css-color-5). @emilio could you open one, so we know what your issue was? If it was mentioned in passing in another issue feel free to link to that.

I had no specific concerns. The only thing I mentioned on the call was that I hadn't reviewed this feature at all, and that I thought flagging such a complex feature as ready to ship when it had not gone through multi-implementor review / etc felt a bit premature, specially given all the churn and specification issues other similar features (like `color-mix()`) had gone through.

**Comment by sesse** [comment]
I don't have a problem of dropping this from Interop.

**Comment by foolip** [comment]
Thanks @sesse! With that, I think we have consensus, so I'll merge https://github.com/web-platform-tests/wpt-metadata/pull/2938.
