### ISSUE TITLE
Read more html

### ISSUE THREAD

**Issue by AucT** [web-platform-tests/interop-2022#194]
### Description

Read more component something like

`<div readmore="100">Readmore string. After 100 chars it will create clickable ... to reveal more</div>`

`<div readmore="100" readmore-button="show more">Readmore string. After 100 chars it will create clickable 'show more' button to reveal more</div>`

### Rationale

Remove js usage for simple useful things.

**Comment by foolip** [comment]
@AucT it looks like you're suggest a new feature in HTML, a `readmore` attribute and a `readmore-button`. Unfortunately, Interop 2023 is not a standards organization so this is out of scope. To quote the [README](https://github.com/web-platform-tests/interop/blob/main/2023/README.md):

> Interop 2023 is not a venue for specifying new features; that work happens in working groups within organizations such as W3C and WHATWG

I'd suggest filing an issue with your use case at https://github.com/whatwg/html/issues/new.
