### ISSUE TITLE
MathML-Core L1

### ISSUE THREAD

**Issue by bkardell** [web-platform-tests/interop-2022#25]
**Description**
MathML-Core is supposed to be in the browser interoperable subset of MathML.  The [spec](https://w3c.github.io/mathml-core/) is a working draft, but it was built with a lot of input along the way and there have even been changes to align in browsers already.  The spec itself should even aync load some tests and results summaries.  They make a nice theme of a group of things we can focus on for specific reasons.  

**Specification**
[Links to the specification(s) for the feature
](https://w3c.github.io/mathml-core/)
**Tests**
Many of the tests are already merged, I believe there are and should still be some more pending...

https://wpt.fyi/results/mathml?label=master&label=experimental&aligned&q=math

**Rationale**
2 browser engines have 'supported MathML', first created in the late 1990s in stable builds for many years. A third did not at all.  The specs were from an earlier era and while the HTML parser specially parses MathML in all browsers there is much that was not highly interoperable nor well aligned in the platform (how specifically should CSS work with Math, for example, or what IDL should elements have) a couple of years ago. Much work has been done to define what we believe should be interoperable answers to lots of those questions, and the third is behind a flag in chromium and getting pretty close.  It would be excellent to have a goal of good interoperability for mathematical text on the web.

**Comment by foolip** [comment]
Per the timeline in https://github.com/web-platform-tests/rfcs/pull/99 it's a bit late for new proposals, but we haven't discussed what to do in this case, so I'll just react and see what we decide together.

I know that MathML hasn't been a priority for Google in a very long time, so my main question here is if there is a path to getting this enabled by default in Chromium in 2022? Is https://opencollective.com/mathml-core-support on track to have enough funds to get this done?

Also, do we have data on the web developer demand for this? I don't doubt that many web developers would say "yes please", but do we know anything about how important it's perceived to be next to other things? I'm not aware of any survey data that helps here, FWIW.

**Comment by jensimmons** [comment]
>Per the timeline in web-platform-tests/rfcs#99 it's a bit late for new proposals

@foolip If you want to enforce the Nov 7 deadline, then we should do so fairly. Fourteen proposals were submitted Nov 8 or later.

**Comment by foolip** [comment]
> >Per the timeline in web-platform-tests/rfcs#99 it's a bit late for new proposals
> 
> 
> 
> @foolip If you want to enforce the Nov 7 deadline, then we should do so fairly. Fourteen proposals were submitted Nov 8 or later.

I don't want to do that, no, but also don't know when we should draw the line. This whole process is a WIP and we'll have to discuss in the next meeting.

**Comment by bkardell** [comment]
> I know that MathML hasn't been a priority for Google in a very long time, so my main question here is if there is a path to getting this enabled by default in Chromium in 2022? 

Definitely.

> Also, do we have data on the web developer demand for this? 

Tricky.  There is obvious demand and need to share mathematical text on the web, yes.  At the same time, you're not wrong that it's not the majority of home pages that will ever contain it, or the majority of web developers who will clamour for it among their top issues.  It's the millions of equations in wikipedia alone, or educational resources, journals, research and so on.  It is an important thing for the web (and society) and an important "niche" that is historically underserved.  I guess there are a lot of very important things (just generally, not even re: the web at all) that would never appear popular in a survey.


That said, I am going to voluntarily close this one myself.  We have far too many things and a lot of debate on different 'kinds' of things we can take up and I feel like omitting this one voluntarily will help us focus. Assuming we can ship in 2022 and progress on having excellent spec and text and compat study, we can possibly see if there is something to take up here in 2023.

**Comment by foolip** [comment]
@bkardell my questions weren't intended to shut down or discourage this proposal, if you'd like to keep it on the table then that's 100% fine. Even though Google hasn't been prioritizing MathML and isn't likely to in 2022 either, if other browser vendors would want to see this included and Igalia could drive it for Interop 2022, that would be a fantastic outcome in my view.

But it's up to you, of course!
