### ISSUE TITLE
Rename Compat 2021 to Interop 2021

### ISSUE THREAD

**Issue by jensimmons** [web-platform-tests/interop-2022#3]
I like that we decided the next version of this project be called Interop 2022.

I believe that when we announce the new 2022 project, we also announce that we've renamed the whole effort — and henceforth will call the 2021 version "Interop 2021". 

It'll be easier for everyone if we just always call this "Interop [Year]'. And don't have legacy baggage to carry along.

**Comment by foolip** [comment]
I think this is a good idea. I've filed https://github.com/web-platform-tests/wpt.fyi/issues/2674 and https://github.com/GoogleChrome/web.dev/issues/6666 about renaming on wpt.fyi and web.dev.

@kypflug @scottlow, Microsoft was supportive of renaming the 2022 iteration of the effort. Do you also think it's a good idea to rename the current effort, and is there content on Microsoft blogs that would need updating?

(It would probably be best to leave a note on most pages saying that the effort was originally called Compat 2021.)

**Comment by kypflug** [comment]
Makes sense to me, I think the consistency is good. I'll take a look at adding a quick editorial note to our previous blogs as needed but I think that's a fairly minor point.

**Comment by foolip** [comment]
@jensimmons noted in https://github.com/web-platform-tests/wpt.fyi/issues/2674#issuecomment-958992786 that I've interpreted this stronger than intended:

> Actually, I don't think the URL needs to be changed. Or old blog posts. I was suggesting that we call it "Interop 2021" from here forward, and say so publicly on day we announce Interop 2022.
>
> We can't change history, so why try. Let the name change be part of the history. And simply use the new name in new content. At least that's my opinion.
>
> A small note could be added to older blog posts that says "in fall 2021, we started calling this effort Interop 2020" for clarity. It seems like that kind of update — on that gets a small note from the future.

I think this makes sense, it's more like we're adding Interop 2021 as an synonym for the effort, not erasing that it was originally called Compat 2021.

**Comment by tomayac** [comment]
The old name apparently was perceived as [awkward](https://thenewstack.io/chrome-dev-summit-2021-its-a-web-evolution-not-revolution/#:~:text=with%20a%20typically%20awkward%20Google%20name%2C%20Compat%202021).

**Comment by jgraham** [comment]
I think we can resolve this one as fixed
