### ISSUE TITLE
OffscreenCanvas

### ISSUE THREAD

**Issue by annevk** [web-platform-tests/interop-2022#31]
**Description**
Enabling usage of canvas in workers.

**Specification**
https://html.spec.whatwg.org/multipage/canvas.html#the-offscreencanvas-interface

**Tests**
https://wpt.fyi/results/html/canvas/offscreen

**Rationale**
I have reason to believe all browsers plan to ship this in the coming year. Making it part of this effort would help ensure implementations are aligned, issues with the specification get resolved, etc.

**Comment by foolip** [comment]
@fserb do you have data about web developer demand for `OffscreenCanvas`? And do you think the existing tests for this feature are sufficient?

**Comment by fserb** [comment]
We do know about [OffscreenCanvas usage](https://chromestatus.com/metrics/feature/timeline/popularity/1624) which at this point is around 27% (in comparison to HTMLCanvasElement which is around 41%). The real useful number would be OffscreenCanvas in workers (where there's no alternative) but we don't have those. 

For the tests, yes. We are very confident they have good coverage. Most of our tests are executed in all 4 configurations (HTMLCanvasElement attached to the DOM, HTMLCanvasElement detached, OffscreenCanvas and OffscreenCanvas in workers). We are actively working on unifying them (cc @yiyix, which is leading this), but for the most part they should already be 90% the same.
