### ISSUE TITLE
[Feature detection and palettes] Add trailing function test to `src: url()` case

### ISSUE THREAD

**Issue by drott** [web-platform-tests/interop-2022#362]
### Test List

https://github.com/web-platform-tests/wpt/pull/40621/files

### Rationale

Create analogous test to trailing invalid trailing function in the `local()` case.

**Comment by nt1m** [comment]
seems fine

**Comment by nairnandu** [comment]
@jgraham or @zcorpan could you review this proposal for Gecko?

**Comment by zcorpan** [comment]
LGTM

**Comment by drott** [comment]
@nairnandu I assume I can go ahead and merge https://github.com/web-platform-tests/wpt/pull/40621 then?
