### ISSUE TITLE
Spreadsheet for tallying positions

### ISSUE THREAD

**Issue by jensimmons** [web-platform-tests/interop-2022#38]
I had already made a spreadsheet in Numbers with the list of all the technology (including the sub-items in each bucket), so I thought I'd drop that list into a Google Doc as a start to our next step. Feel free to copy & paste this into another sheet if you'd like. Items are listed in order of when proposals were submitted.

It's here: https://docs.google.com/spreadsheets/d/1BWAwrBywedi7kBEij8NHU84UJKu6-SGR3ZykjM1l_0g/edit?usp=sharing

@foolip

**Comment by foolip** [comment]
Perfect, thanks Jen! I'll make a copy with some instructions and share that around.

**Comment by foolip** [comment]
Alright, the [Interop 2022 positions](https://docs.google.com/spreadsheets/d/1SQF81pf5hxFE9dMZcJGXE2RNmb7AjFHg6mnkf9KOEC0/edit?usp=sharing) has instructions and a sheet to copy for everyone participating in the process. Here are the different "positions" I landed on:

Shorthand | Meaning
-- | --
Support | Include in Interop 2022 metric
Oppose | Don't include in Interop 2022 effort at all
Neutral | Don't mind including in Interop 2022 if others support
Investigate | Don't include as a metric, but do further work under the Interop 2022 umbrella, such as researching the current state of interop, writing tests, or moving the spec forward in the appropriate standards groups.

I didn't go with a P0-P3 priority which was also suggested, because these are used differently in different projects / bug trackers, and also because I don't think it could represent "Investigate" well.

**Comment by foolip** [comment]
After a discussion in the Matrix rooms with @jgraham and @annevk I've updated the definitions in the table a bit.

**Comment by jensimmons** [comment]
Two things:
1) We need columns or tab for each vendor, so people have a place to vote.
2) The sheet is currently view-only.

Also, who is voting?
- Google
- Apple
- Mozilla
- Igalia
... anyone else? What about Microsoft? Have you reached out to them to keep them in the loop throughout the process?

**Comment by meyerweb** [comment]
>     1. We need columns or tab for each vendor, so people have a place to vote.
>     2. The sheet is currently view-only.

I think the idea is for each team (or other org) to copy the sheet to their own Google Drive, and then edit that one.

**Comment by jgraham** [comment]
> Also, who is voting?

No one. Per the initial RFC we are "seeking to identify […] areas that everyone would be happy to include" i.e. it's a process aimed at achieving consensus, not a vote.

**Comment by foolip** [comment]
> We need columns or tab for each vendor, so people have a place to vote.

@jensimmons that was my original intention, but with the "Sub-position" and comment columns, that seemed impractical, with 3 columns per org. However, I agree a single sheet would be great for an overview, and have added a [Summary sheet](https://docs.google.com/spreadsheets/d/1SQF81pf5hxFE9dMZcJGXE2RNmb7AjFHg6mnkf9KOEC0/edit#gid=688015744) for that. That can be one of the last things we fill in, I think.

I'll grant edit access to anyone who wants to edit there directly. Or folks can make a copy and then share that via URL. It depends on whether people want to share their in-progress positions or not, either is fine I think.

Regarding who participates, I think your list is accurate. Microsoft are participating, and I think I saw both @dlibby- and @scottlow folks in yesterday's meeting.

As @jgraham says the idea is finding the common ground. Ultimately https://github.com/web-platform-tests/rfcs/pull/99 needs to be accept, but the idea is to have a joint understanding, making the RFC a formality.

I haven't stated it in the RFC or elsewhere, but I think it's important that there's no process advantage from having multiple orgs contribute to a single browser engine, and I think we're steering clear of that. If we had voting I think we'd need something like one vote per engine, which would be a complication.

I suspect we'll identify lots of things to improve about the process for next time though :)

**Comment by jensimmons** [comment]
Could you put the Sub-proposal column (one copy, on the left, for reference) and five copies of the Sub-position column (for each of the five orgs) in the Summary Tab instead of the Position column? Then we could all post our positions for all the items on one page. 

Perhaps everyone could post their positions in the shared sheet by **end of day on Tuesday.** It would be helpful, I believe to be able to see everyone's position at least one day before meeting on Thursday. 

If we wait until the last minute to share our positions (perhaps only in private copies of the sheet, shared via video conferencing during the meeting) — we will spend the whole meeting simply digesting what everyone has decided. Talking the list aloud. We won't be able to make much progress.

If instead we can all see where we are at on Tuesday night / Wednesday morning, then we'll have a day to think it through, and can come to Thursday's meeting with a much clearly sense of which items will need further discussion.

**Comment by foolip** [comment]
@jensimmons that sounds like a good solution, I'll edit the spreadsheet Monday morning. I also agree that having positions earlier would be better, I'll request it on the email thread if nobody beats me to it.

**Comment by foolip** [comment]
Alright, I've gone ahead and update the spreadsheet now, creating a new [Sub-proposal summary](https://docs.google.com/spreadsheets/d/1SQF81pf5hxFE9dMZcJGXE2RNmb7AjFHg6mnkf9KOEC0/edit#gid=4939874) sheet and updating the instructions.

Having tried to fill in some of it for Google, and repeating work, I think it will be easiest for folks to start from a copy of "Template" and then copy from that into the summary when done.

Suggestions for further simplification/improvements welcome.

**Comment by jgraham** [comment]
I don't think we can commit to the Tuesday timetable, since we need time to reconsider the proposals that have undergone recent updates.

**Comment by jensimmons** [comment]
In email @foolip wrote:
> For next year we should probably only have one level of proposals to simplify.

In many ways, the “buckets” (or themes) are for marketing purposes (later), and not for deciding-on-technology  purposes. 

I don’t really see any point to expressing support for (or rejection of) an overall theme separate from the individual pieces. If, for example, an organization expressed support for the Form Controls theme to be included in Interop 2022, but then rejected each & every specific suggestion — what would that mean? It’s beyond the deadline to suggest new items… so I wouldn’t expect another round to define new form control items… it seems that all the matters at this point are the details. If an organization supports any of the form control items, then they support the bucket. If they support none of the items, then they reject the bucket. No need to “vote”(not vote) on the buckets alone.

**Comment by foolip** [comment]
Closing this since the spreadsheet has been filled out and used in https://github.com/web-platform-tests/interop-2022/issues/39.

@jensimmons indeed expressing support for the buckets independent of their contents wasn't very meaningful, and we didn't really use that sheet. We can skip that next time.
