### ISSUE TITLE
Focus area labels

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop-2022#42]
For the purposes of tracking tests for each [accepted proposal](https://github.com/web-platform-tests/interop-2022/labels/accepted) in Interop 2022, we will use the labeling system provided on wpt.fyi.

Here are the 10 areas/labels, linked only where labeling is done:

- [`interop-2022-cascade`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-cascade) for https://github.com/web-platform-tests/interop-2022/issues/5
- [`interop-2022-color`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-color) for https://github.com/web-platform-tests/interop-2022/issues/20
- [`interop-2022-contain`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-contain) for https://github.com/web-platform-tests/interop-2022/issues/19
- [`interop-2022-dialog`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-dialog) for https://github.com/web-platform-tests/interop-2022/issues/12
- [`interop-2022-forms`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-forms) for https://github.com/web-platform-tests/interop-2022/issues/11
- [`interop-2022-scrolling`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-scrolling) for https://github.com/web-platform-tests/interop-2022/issues/14 + https://github.com/web-platform-tests/interop-2022/issues/21
- [`interop-2022-subgrid`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-subgrid) for https://github.com/web-platform-tests/interop-2022/issues/1
- [`interop-2022-text`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-text) for https://github.com/web-platform-tests/interop-2022/issues/13
- [`interop-2022-viewport`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-viewport) for https://github.com/web-platform-tests/interop-2022/issues/4
- [`interop-2022-webcompat`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-webcompat) for https://github.com/web-platform-tests/interop-2022/issues/9

[Query for all of these labels together](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=%20label%3Ainterop-2022-cascade%20or%20label%3Ainterop-2022-color%20or%20label%3Ainterop-2022-contain%20or%20label%3Ainterop-2022-dialog%20or%20label%3Ainterop-2022-forms%20or%20label%3Ainterop-2022-scrolling%20or%20label%3Ainterop-2022-subgrid%20or%20label%3Ainterop-2022-typography%20or%20label%3Ainterop-2022-viewport%20or%20label%3Ainterop-2022-webcompat)

**Comment by nt1m** [comment]
@foolip I tagged the interop-2022-color ones, see https://github.com/web-platform-tests/interop-2022/issues/20#issuecomment-1006337706

**Comment by jensimmons** [comment]
Are the tests from Compat 2021 labeled in the same way? Where can I find those labels/links to searches?

**Comment by nt1m** [comment]
@jensimmons The test lists are stored in text files: https://github.com/Ecosystem-Infra/wpt-results-analysis/tree/main/compat-2021

**Comment by foolip** [comment]
@jensimmons @nt1m I had labeled Compat 2021 tests as just `interop-2021`, but I've now [split them](https://github.com/web-platform-tests/wpt-metadata/pull/2351):

- [`interop-2021-aspect-ratio`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2021-aspect-ratio)
- [`interop-2021-flexbox`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2021-flexbox)
- [`interop-2021-grid`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2021-grid)
- [`interop-2021-position-sticky`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2021-position-sticky)
- [`interop-2021-transforms`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2021-transforms)

[Query for all of these labels together](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2021-aspect-ratio%20or%20label%3Ainterop-2021-flexbox%20or%20label%3Ainterop-2021-grid%20or%20label%3Ainterop-2021-position-sticky%20or%20label%3Ainterop-2021-transforms)

**Comment by foolip** [comment]
All of the labels are applied and there's nothing more to do on this issue.
