### ISSUE TITLE
Improve the Interop Dashboard

### ISSUE THREAD

**Issue by jensimmons** [web-platform-tests/interop-2022#45]
The Compat 2021 dashboard:
https://wpt.fyi/compat2021?feature=summary

Let's have a discussion about how we could redesign this page to better explain the project to folks who are interested.

**Comment by jensimmons** [comment]
I'd like to see an improved dashboard that:

1. More clearly explains that this is a project testing specific areas of concern to web developers, and not testing the overall quality of browser engines. 
2. Helps people see more quickly & obviously which technologies are making up the score, and how each is doing in each browser. Both the over 15 technologies, and the specific technologies web developers are using inside each of those categories. 
3. Provides links to the web specifications and perhaps MDN for all of the technologies making up the 15 categories — so developers can discover new things. 
4. Provides direct links for browser engineers to find the relevant tests so they can work to improve their score.
5. Provides the combined score as planned, and easy ways to see the 2022 results & 2021 results... leading to an understanding why the graph & main score suddenly changed from "96 92 92" to the new scores. 

I'd suggest fewer words, more diagrams / labels / graph lines. Not relying on hover. Using more expected/commonly-used UI elements to display the information and provide controls.

**Comment by foolip** [comment]
@argyleink we agreed in the meeting yesterday that more feedback on the dashboard can go in this issue, so mentioning you here so you won't miss it :)
