### ISSUE TITLE
Carryover evaluation: Border Image

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop-2022#456]
Let's evaluate whether to continue the Border Image focus area in Interop 2024.

Original proposal: https://github.com/web-platform-tests/interop/issues/146 by @jsnkuhn

Tests:
- [All tests](https://wpt.fyi/results/css/css-backgrounds?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-cssborderimage)
- [Failing tests](https://wpt.fyi/results/css/css-backgrounds?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-cssborderimage%20status%3A%21ok%20status%3A%21pass)

We should also consider whether we should add tests for 2024.

**Comment by foolip** [comment]
Looking [unlabeled tests](https://wpt.fyi/results/css/css-backgrounds?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=%21label%3Ainterop-2023-cssborderimage%20border%20image), there are 3 that fail in Safari. They were added in these PRs:

- https://github.com/web-platform-tests/wpt/pull/40715
- https://github.com/web-platform-tests/wpt/pull/40731

@TalbotG @fantasai do you think web developers are likely to run into these cases?

**Comment by TalbotG** [comment]
@foolip Philip,
I do not know. I do not think so.

**Comment by dholbert** [comment]
> The only remaining failure here is in Firefox and linked to https://bugzilla.mozilla.org/show_bug.cgi?id=1819485. cc @dholbert who was the last to comment on the bug.

Yup, as far as I can tell, the two tests there are real bugs. Thanks for the nudge -- this prompted me to poke at that bug a bit and get a bit closer to understanding the failure (though I think we're gated on someone from our WebRender team to fix it).
