### ISSUE TITLE
Tests with non-OK/PASS/FAIL results

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop-2022#48]
In the Jan 13 meeting I took an action item to look into tests that fail in some other way than the usual, which usually means ERROR or TIMEOUT. When querying on wpt.fyi, it also includes `status:missing`, and I also agreed to look into tests that have different numbers of subtests in different browsers.

I've looked through the 36 tests found by the [`!(status:ok or status:pass or status:fail) and (label:interop-2021-aspect-ratio or label:interop-2021-flexbox or label:interop-2021-grid or label:interop-2021-position-sticky or label:interop-2021-transforms or label:interop-2022-cascade or label:interop-2022-color or label:interop-2022-contain or label:interop-2022-dialog or label:interop-2022-forms or label:interop-2022-scrolling or label:interop-2022-subgrid or label:interop-2022-text or label:interop-2022-viewport or label:interop-2022-webcompat)`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=%21%28status%3Aok%20or%20status%3Apass%20or%20status%3Afail%29%20and%20%28label%3Ainterop-2021-aspect-ratio%20or%20label%3Ainterop-2021-flexbox%20or%20label%3Ainterop-2021-grid%20or%20label%3Ainterop-2021-position-sticky%20or%20label%3Ainterop-2021-transforms%20or%20label%3Ainterop-2022-cascade%20or%20label%3Ainterop-2022-color%20or%20label%3Ainterop-2022-contain%20or%20label%3Ainterop-2022-dialog%20or%20label%3Ainterop-2022-forms%20or%20label%3Ainterop-2022-scrolling%20or%20label%3Ainterop-2022-subgrid%20or%20label%3Ainterop-2022-text%20or%20label%3Ainterop-2022-viewport%20or%20label%3Ainterop-2022-webcompat%29) query.

# `<dialog>` and `::backdrop`

[/html/semantics/interactive-elements/the-dialog-element/backdrop-receives-element-events.html](https://wpt.fyi/results/html/semantics/interactive-elements/the-dialog-element/backdrop-receives-element-events.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is TIMEOUT in Safari with the single subtest being NOTRUN. It's linked to https://webkit.org/b/233072 which was recently fixed, confirmed with [Safari + WebKitGTK](https://wpt.fyi/results/html/semantics/interactive-elements/the-dialog-element/backdrop-receives-element-events.html?run_id=6276661696790528&run_id=5083300671520768).

# Flexbox

[/css/css-flexbox/break-nested-float-in-flex-item-001-print.html](https://wpt.fyi/results/css/css-flexbox/break-nested-float-in-flex-item-001-print.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) and [-002-print.html](https://wpt.fyi/results/css/css-flexbox/break-nested-float-in-flex-item-002-print.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) aren't run in Safari. Already discussed in https://github.com/web-platform-tests/interop-2022/issues/2#issuecomment-983423769 and we should drop these tests.

# Form Controls

[/dom/events/Event-dispatch-click.html](https://wpt.fyi/results/dom/events/Event-dispatch-click.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is TIMEOUT in Chrome, but that's the expected failure mode when the event doesn't fire.

The 6 form-submit* tests in [/html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/](https://wpt.fyi/results/html/browsers/browsing-the-web/navigating-across-documents/replace-before-load?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-forms) are ERROR in Safari. There's a `NoSuchFrameException` raised in Python so probably there's some WebDriver issue underneath this.

The 2 form-requestsubmit-during-* tests in the same directory are TIMEOUT in Safari. Needs investigation.

5 form-validation-* tests in [/html/semantics/forms/constraints/](https://wpt.fyi/results/html/semantics/forms/constraints?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-forms) have MISSING tests because two different tests are created (and fail) in Safari than in Chrome and Firefox. These tests are about week/month and like https://github.com/web-platform-tests/wpt-metadata/pull/2401 should be excluded, but the tests need to be fixed to run the same subtests in all browsers first to see if there are other failing tests that aren't about week/month.

[/html/semantics/forms/constraints/infinite_backtracking.html](https://wpt.fyi/results/html/semantics/forms/constraints/infinite_backtracking.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is TIMEOUT in Firefox, presumably because it has the bug the test is probing for.

[/html/semantics/forms/form-submission-0/form-double-submit-multiple-targets.html](https://wpt.fyi/results/html/semantics/forms/form-submission-0/form-double-submit-multiple-targets.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is TIMEOUT in Safari.

[/html/semantics/forms/form-submission-0/form-double-submit-to-different-origin-frame.html](https://wpt.fyi/results/html/semantics/forms/form-submission-0/form-double-submit-to-different-origin-frame.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is TIMEOUT in Firefox and Safari, but also fails in Chrome, tracked by https://crbug.com/1087077. I would guess one of the events never fire in Firefox/Safari and that the timeout is legit.

The rel-* tests in [/html/semantics/forms/form-submission-target/](https://wpt.fyi/results/html/semantics/forms/form-submission-target?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) are TIMEOUT in Safari, but all of the subtests pass. This very unusual and needs investigation.

[/html/semantics/forms/textfieldselection/select-event.html](https://wpt.fyi/results/html/semantics/forms/textfieldselection/select-event.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is TIMEOUT in Safari after the first subtest times out. Looks like the "select" event never fires and the test is OK.

[/html/semantics/forms/textfieldselection/selection-not-application.html](https://wpt.fyi/results/html/semantics/forms/textfieldselection/selection-not-application.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) has fewer subtests in Safari, the week/month ones [aren't created](https://github.com/web-platform-tests/wpt/blob/ee6da9d71d0268d7fdb04e8e5b26858f46ee0cc4/html/semantics/forms/textfieldselection/selection-not-application.html#L17-L20). This actually seems fine from a metrics point of view if we score each browser individually.

[/html/semantics/forms/textfieldselection/selection-start-end.html](https://wpt.fyi/results/html/semantics/forms/textfieldselection/selection-start-end.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is an overall TIMEOUT in Safari, with a bunch of NOTRUN subtests. What's odd is that no subtest has timed out. Needs investigation.

[/html/semantics/forms/textfieldselection/textfieldselection-setRangeText.html](https://wpt.fyi/results/html/semantics/forms/textfieldselection/textfieldselection-setRangeText.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is an overall TIMEOUT in Safari after one of the subtests is TIMEOUT due to an event not being fired. The test seems OK, but it's not obvious how to score this.

[/html/semantics/forms/textfieldselection/textfieldselection-setSelectionRange.html](https://wpt.fyi/results/html/semantics/forms/textfieldselection/textfieldselection-setSelectionRange.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is TIMEOUT in Safari because one subtest is TIMEOUT. Also tricky for scoring.

[/html/semantics/forms/the-input-element/range-restore-oninput-onchange-event.html](https://wpt.fyi/results/html/semantics/forms/the-input-element/range-restore-oninput-onchange-event.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is TIMEOUT in Safari, both harness and subtests. An event isn't fired, test seems OK.

# Grid

[/css/css-grid/grid-definition/grid-limits-001.html](https://wpt.fyi/results/css/css-grid/grid-definition/grid-limits-001.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is TIMEOUT in Safari. I've tried running it locally and it just shows a white page, but no console errors.

# Scrolling

There are 3 tests that use `new test_driver.Actions().scroll(...)` and either ERROR or TIMEOUT in Firefox/Safari:

- [/css/css-overscroll-behavior/overscroll-behavior.html](https://wpt.fyi/results/css/css-overscroll-behavior/overscroll-behavior.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is ERROR in both Firefox and Safari.
- [/css/css-scroll-snap/input/snap-area-overflow-boundary.html](https://wpt.fyi/results/css/css-scroll-snap/input/snap-area-overflow-boundary.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is ERROR in Firefox and TIMEOUT in Safari.
- [/css/css-scroll-snap/snap-at-user-scroll-end.html](https://wpt.fyi/results/css/css-scroll-snap/snap-at-user-scroll-end.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is ERROR in both Firefox and Safari.

https://bugzil.la/1746601 is the Gecko bug about this testdriver API. The harness errors can probably be fixed with the proper `t.step_func` wrapping or similar.

[/css/css-scroll-snap/input/keyboard.html](https://wpt.fyi/results/css/css-scroll-snap/input/keyboard.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is TIMEOUT in Firefox and Safari, but the first test runs and fails in Firefox. I don't think this is due to a missing testdriver.js API, but it needs investigation.

[/css/cssom-view/scroll-behavior-smooth.html](https://wpt.fyi/results/css/cssom-view/scroll-behavior-smooth.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned) is ERROR in Chrome and TIMEOUT in Safari. Needs investigation.

**Comment by gsnedders** [comment]
> The rel-* tests in /html/semantics/forms/form-submission-target/ are TIMEOUT in Safari, but all of the subtests pass. This very unusual and needs investigation.

The load event never fires, so the harness behaves like it doesn't know if there are more tests to be registered. See https://bugs.webkit.org/show_bug.cgi?id=235407.

**Comment by foolip** [comment]
After https://github.com/web-platform-tests/wpt/pull/32468 I can't find any more cases of inconsistent subtests across browsers except those cases where no tests ran due a harness error or timeout.

**Comment by gsnedders** [comment]
> The 6 form-submit* tests in /html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/ are ERROR in Safari. There's a NoSuchFrameException raised in Python so probably there's some WebDriver issue underneath this.

This is the fact wptrunner doesn't support the top-level test page being navigated during the test, and [html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/resources/helpers.js](https://github.com/web-platform-tests/wpt/blob/62c22e4362e19418022e03ca4f5bea76b998fa3f/html/browsers/browsing-the-web/navigating-across-documents/replace-before-load/resources/helpers.js#L54) is calling `history.back` which in Safari is navigating the to-level document.

> The 2 form-requestsubmit-during-* tests in the same directory are TIMEOUT in Safari. Needs investigation.

https://bugs.webkit.org/show_bug.cgi?id=235947, though clearly the tests could be fixed to not timeout.
