### ISSUE TITLE
Box Alignment on Block Boxes

### ISSUE THREAD

**Issue by fantasai** [web-platform-tests/interop-2022#6]
The CSS Alignment spec defines various box alignment properties to work on in-flow and abspos block boxes, but this is not implemented. It would be good to get these properties working across the board in CSS, and protect against the potential for bugwards-compat from stylesheet errors.

https://www.w3.org/TR/css-align-3/

**Comment by jgraham** [comment]
Apologies, I just added an issue template for porposals, which I should have done much earlier.

Would you be able to rewrite the issue description to match that [template](https://github.com/web-platform-tests/interop-2022/issues/new?assignees=&labels=proposal&template=proposal.md&title=)?

**Comment by jensimmons** [comment]
@fantasai Could you track down the bug tickets for each engine?

**Comment by foolip** [comment]
Based on https://wpt.fyi/results/css/css-align?run_id=5068826774339584&run_id=5670550115450880&run_id=5636164204625920 I suspect there are no tests for this, because there are no tests that fail everywhere.

**Comment by foolip** [comment]
Based on the Dec 9 meeting, with outcomes summarized in https://github.com/web-platform-tests/interop-2022/issues/39#issuecomment-991001758, we won't include Box Alignment on Block Boxes in Interop 2022.

I note that there does seem to be interest in implementing this, however, and hopefully tests will be added as part of that.
