### ISSUE TITLE
Naming of Focus Areas

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/interop-2022#61]
Currently the dashboard (https://github.com/web-platform-tests/wpt.fyi/pull/2744) has:

2022:
* Cascade Layers
* Color
* Containment
* \<dialog> and ::backdrop
* Forms
* Scrolling
* Subgrid
* Text
* Viewport Units
* Web Compat

2021:
* Aspect Ratio
* Flexbox
* Grid
* position: sticky
* Transforms

Investigate:
* Editing, contenteditable and execCommand
* Pointer and Mouse Events
* Viewport Measurement

For labels (https://github.com/web-platform-tests/interop-2022/issues/42) we have:

 * interop-2022-cascade
 * interop-2022-color
 * interop-2022-contain
 * interop-2022-dialog
 * interop-2022-forms
 * interop-2022-scrolling
 * interop-2022-subgrid
 * interop-2022-text
 * interop-2022-viewport
 * interop-2022-webcompat
 * interop-2021-aspect-ratio
 * interop-2021-flexbox
 * interop-2021-grid
 * interop-2021-position-sticky
 * interop-2021-transforms

---

Are these the names we want to use for everything? Do we want to prefix the names of some of the CSS ones with "CSS"? "Color" especially seems exceptionally vague, but even Cascade Layers and Containment are mostly talked about publicly with "CSS" attached.

**Comment by foolip** [comment]
"Color" is one that I struggled a bit with and would be open to other suggestions, like perhaps "Color Spaces & Color Functions", although that's just a tad long.

I think that adding in "CSS" in a consistent way will be tricky, in particular I don't know about "&lt;dialog> and ::backdrop", "Viewport Units" and "Aspect Ratio". But again, open to suggestions.

**Comment by jensimmons** [comment]
1) If we do add "CSS" to something, let's not have confusion about alphabetical order. That was a problem in 2021. "CSS Transforms" got weird in the order.

2) Imho, the test labels are totally fine. (aka `interop-2022-color`). It's the wording in the table that I'm wondering about. It feels like the super short keywords for test labels have been directly translated to human-readable names in the table, and a lot of meaning & context is lost.

3) As for names... in the table & dropdown, and presumably in the blog posts we are writing...

"Forms" for instance, would be better "Form submission" perhaps. It's not a bucket of all the tests for everything having to do with forms or form controls.

"Color" could perhaps be "Color Spaces & Functions".

"Text" might better be "Typography" for the human readable form. Or font something. Let people know what this is about. It's not about the painting of unicode characters. It's about `font-*` CSS.

"Scrolling" is actually about scroll snap, scroll behavior and over scroll behavior. I'm not sure what could be the right longer-but-not-too-long phrase.

**Comment by foolip** [comment]
I'll put this on the agenda for tomorrow. My reactions inline:

> "Forms" for instance, would be better "Form submission" perhaps. It's not a bucket of all the tests for everything having to do with forms or form controls.

There's a bunch more than form submission in https://github.com/web-platform-tests/interop-2022/issues/11#issuecomment-976047408 and the labeled tests. The `appearance` property, events and validation are the big ones. If we want to make it just a bit longer, "Form Controls" would work, but isn't really more specific.

> "Color" could perhaps be "Color Spaces & Functions".

Yep, that seems good to me.

> "Text" might better be "Typography" for the human readable form. Or font something. Let people know what this is about. It's not about the painting of unicode characters. It's about `font-*` CSS.

It did start out as "Typography" in your proposal (https://github.com/web-platform-tests/interop-2022/issues/13), but the inclusion of text encodings is what made that label not work. I don't think "Text" is great, but don't know what exactly to suggest. Maybe "Fonts & Encodings" if we think the `ic` unit can fit under the "Fonts" umbrella? Or "Typography & Encodings"?

> "Scrolling" is actually about scroll snap, scroll behavior and over scroll behavior. I'm not sure what could be the right longer-but-not-too-long phrase.

I rather like this label, the only issue is that it doesn't cover everything scrolling-related. But that's the case for many other areas too.

**Comment by foolip** [comment]
In the meeting just now we've decided to rename these:
- Color Spaces and Functions (more precise, doesn't suggest `color` is included)
- Dialog Element
- Typography and Encodings
- Sticky Positioning
- Editing, contenteditable, and execCommand

Not great, to be revisited in this issue tomorrow:
- Forms

**Comment by foolip** [comment]
The renaming has been done, except for Forms which remains "Forms". @jensimmons would you like to revisit that in a future meeting?

**Comment by jensimmons** [comment]
We used "Form Fixes" in our blog post. But I don't know that there's enough momentum behind a desire for a change to push this. If folks want to stick with "Forms", we would be ok with that.

**Comment by foolip** [comment]
Alright, let's stick with "Forms".
