### ISSUE TITLE
README.md has a dead link

### ISSUE THREAD

**Issue by cdcarson** [web-platform-tests/interop-2022#66]
https://github.com/web-platform-tests/rfcs/blob/compat_2022/rfcs/interop_2022.md linked to from the README does not exist.

**Comment by foolip** [comment]
Thanks for reporting! That's because the pull request was merged and the branch removed. I'll fix.

**Comment by foolip** [comment]
I fixed this in https://github.com/web-platform-tests/interop-2022/commit/5228ed0b4066b0b28714af36bbe63d969ad03bd1.
