### ISSUE TITLE
Agenda for March 24 meeting

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop-2022#69]
Here's the agenda for our meeting tomorrow:

- https://github.com/web-platform-tests/interop-2022/issues/68
- Test change review: https://github.com/web-platform-tests/wpt-metadata/pull/2610
- Test and score updates
- Investigation effort updates
  - https://github.com/web-platform-tests/interop-2022-editing/issues/1
  - Pointer and Mouse Events
    - https://github.com/web-platform-tests/interop-2022-pointer created
  - https://github.com/web-platform-tests/interop-2022/issues/41
- https://github.com/web-platform-tests/wpt/pull/33339 is stuck

Previous meeting: https://github.com/web-platform-tests/interop-2022/issues/67

**Comment by foolip** [comment]
Rough meeting notes:

## https://github.com/web-platform-tests/wpt-metadata/pull/2610

Philip: This was automatically merged. Please review for next time to make sure tests are OK.

Sam: Only PRs from branches in the repo are merged.

Philip: Action item to avoid merging automatically if we're adding or removing interop-* labels. (File an issue.)

Sam: Or require review for all labels.

## https://github.com/web-platform-tests/wpt/pull/33339

Sam: Failing infra tests, it's on my TODO list.

James: Seems like a safaridriver issue? Connection errors?

Sam: It's testdriver.js bits failing, other things are fine.

Sam: Also note that Safari stable is out of date. `softwareupdate` isn't (reliably) finding the update on Azure Pipelines. There will be a workaround!

## Investigation updates

[**Editing, contenteditable, and execCommand**](https://github.com/web-platform-tests/interop-2022-editing)

James: Did we find anyone from WebKit? I know the Gecko and Chromium folks. Then we need to set some goals.

Jon: I can work on finding a contact today.

[**Pointer and Mouse Events**](https://github.com/web-platform-tests/interop-2022-pointer)

Philip: Rob or I will create a README and issue.

Simon: Howard and I interested in this workstream, have begun to collect issues.

James and Jon to find contacts.

[**Viewport Measurement**](https://github.com/web-platform-tests/interop-2022/issues/41)

@jensimmons do you have an update on this? It looks like the next steps are meeting scheduling, but feel free to comment here or on the issue if there's any action needed by the group.

**Comment by jensimmons** [comment]
As for who's representing Apple for the Point and Mouse Events investigation — that’s going to be Wenson Hsieh @whsieh, Devin Rousso @dcrousso, and Antoine Quint @graouts.

**Comment by jensimmons** [comment]
As for next steps, yes, a meeting for Viewport Measurements is next. And setting up ways to work async, given the _very_ wide range of timezones in the group. 

Could someone with privileges setup a new repo for the Viewport investigation? Much like: https://github.com/web-platform-tests/interop-2022-pointer @foolip perhaps?

**Comment by foolip** [comment]
@jensimmons for sure, I've created https://github.com/web-platform-tests/interop-2022-viewport now! https://github.com/orgs/web-platform-tests/teams/interop-2022 has write access, everyone feel free to edit the README directly to fill in those TODOS.

(I didn't create a Matrix chat room, because @jensimmons mentioned in a meeting a long and unsuccessful struggle to get it working, and it makes no sense to have a chat room for this without Jen.)
