### ISSUE TITLE
Extend Interop 2022 Viewport tests

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/interop-2022#70]
Specifically, the suggestion is to extend this to:

https://wpt.fyi/results/css/css-values?label=master&label=experimental&product=chrome&product=firefox&product=safari&product=webkitgtk&q=label%3Ainterop-2022-viewport%20or%20%2Fcss%2Fcss-values%2Fviewport-units-keyframes.html%20or%20%2Fcss%2Fcss-values%2Fviewport-units-media-queries.html%20or%20%2Fcss%2Fcss-values%2Fviewport-units-invalidation.html%20or%20%2Fcss%2Fcss-values%2Fviewport-units-writing-mode.html%20or%20%2Fcss%2Fcss-values%2Fviewport-units-compute.html

i.e., adding:

* /css/css-values/viewport-units-keyframes.html
* /css/css-values/viewport-units-media-queries.html
* /css/css-values/viewport-units-invalidation.html
* /css/css-values/viewport-units-writing-mode.html
* /css/css-values/viewport-units-compute.html

Currently, we have only a very basic test that the viewport units can be parsed, and this adds functional tests.

**Comment by jgraham** [comment]
@hiikezoe  @emilio I assume we're OK with adding these tests to the metric (seems like Firefox already passes them at least). Did we write any tests/find any interop issues during implementation that should also be included?

**Comment by emilio** [comment]
We did find a subtle correctness issue and landed a test for https://bugzilla.mozilla.org/show_bug.cgi?id=1764279. WebKit has some extra bugs here in the sense that they use the root viewport units. Hard to test the difference between the new units tho, since there's no guarantee they would be different.

**Comment by foolip** [comment]
The added test is https://wpt.fyi/results/css/css-values/viewport-units-writing-mode-font-size.html.

@andruud took a look and thinks that looks OK.

@gsnedders would the WebKit team be happy adding this test as well?

**Comment by gsnedders** [comment]
> The added test is https://wpt.fyi/results/css/css-values/viewport-units-writing-mode-font-size.html.
> 
> @andruud took a look and thinks that looks OK.
> 
> @gsnedders would the WebKit team be happy adding this test as well?

Yes.

**Comment by foolip** [comment]
I have labeled the new tests here:
https://github.com/web-platform-tests/wpt-metadata/pull/2726
https://github.com/web-platform-tests/wpt-metadata/pull/2727
