### ISSUE TITLE
Some interop-2022-cascade tests cover too many things

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop-2022#74]
This one tests `document.adoptedStylesheets` which WebKit does not implement: https://wpt.fyi/results/css/css-cascade/layer-statement-before-import.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-cascade

This one tests `@property`: https://wpt.fyi/results/css/css-cascade/layer-cssom-order-reverse.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=label%3Ainterop-2022-cascade

Worth splitting or removing those tests from Interop 2022

**Comment by gsnedders** [comment]
see also https://github.com/web-platform-tests/interop-2022/issues/5

I think we basically just want to use `assert_implements_optional` for these?

**Comment by foolip** [comment]
@xiaochengh do you think these tests can be split (perhaps using variants) or use `assert_implements_optional` to avoid the hard dependency on these features?

**Comment by foolip** [comment]
Discussed in https://github.com/web-platform-tests/interop-2022/issues/77. General preference is that we split the tests if at all possible. Using `assert_implements_optional` would raise the question of what features are optional? Every other spec?

**Comment by xiaochengh** [comment]
Is there a list of tests we'd like to split, and a guideline how to split them?

**Comment by nt1m** [comment]
@xiaochengh See the first comment, essentially css/css-cascade/layer-statement-before-import.html and css/css-cascade/layer-cssom-order-reverse.html

**Comment by foolip** [comment]
The tests were split in https://github.com/web-platform-tests/wpt/pull/34081. Thanks @xiaochengh!
