### ISSUE TITLE
Extend interop-2022-cascade tests

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/interop-2022#75]
I propose adding:

css/css-cascade/all-prop-revert-layer.html
css/css-cascade/revert-layer-013.html
css/css-cascade/revert-layer-014.html
css/css-cascade/revert-layer-015.html

Not sure if the first one is appropriate given the scoring is based on the number of supported CSS properties, but the other 3 seem reasonable (they test a crash in WebKit that was recently fixed).

**Comment by emilio** [comment]
No, sounds good.

**Comment by foolip** [comment]
@andruud can you review the suggested additions?

**Comment by andruud** [comment]
LGTM

**Comment by foolip** [comment]
Discussed in https://github.com/web-platform-tests/interop-2022/issues/77. We have support from someone from each browse engine, so we'll add these tests.

**Comment by foolip** [comment]
I have labeled these tests in https://github.com/web-platform-tests/wpt-metadata/pull/2728.
