### ISSUE TITLE
Agenda for May 12 meeting

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop-2022#77]
Here's the agenda for our meeting tomorrow:

- Test change review:
  - https://github.com/web-platform-tests/interop-2022/issues/70
  - https://github.com/web-platform-tests/interop-2022/issues/74
  - https://github.com/web-platform-tests/interop-2022/issues/75
  - https://github.com/web-platform-tests/interop-2022/issues/76
- Investigation effort updates
  - Editing (@jgraham): https://github.com/web-platform-tests/interop-2022-editing/issues/1
  - Pointer and Mouse Events (@flackr): https://github.com/web-platform-tests/interop-2022-pointer/issues/3
  - Viewport (@jensimmons): https://github.com/web-platform-tests/interop-2022/issues/41
- FYI: Interop 2022 score updates
- FYI: https://github.com/web-platform-tests/interop-2022/issues/71 meeting happening Thu, May 19 15:00-16:00 UTC

Previous meeting: https://github.com/web-platform-tests/interop-2022/issues/72

**Comment by foolip** [comment]
_Rough meeting notes_

**Test change review**

Action item: Labeling #70, #75 and #76, following up on #74.

**Comment by dontcallmedom** [comment]
> @robnyman asks Apple and Microsoft to check for participation. And we're not sure which time is correct, @dontcallmedom can you confirm if two meetings are happening?

Two meetings are happening - one tomorrow at 2pm UTC, another one on Thursday at 3pm UTC.
