### ISSUE TITLE
Reinstate/add showPicker() tests

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop-2022#81]
For Forms, we originally had show-picker.html and show-picker-cross-origin-iframe.html labeled for Interop 2022.

In discussion with @ziransun we found that show-picker.html has since been renamed (https://github.com/web-platform-tests/wpt/pull/33465) and then accidentally dropped from the test list in https://github.com/web-platform-tests/wpt-metadata/commit/6eea9fef75bb8ec3a6d26776b03625dc481158bf.

Reinstating the renamed test is probably uncontroversial, but @ziransun has also added a new test so I'd like to suggest adding both. Here they are:

https://wpt.fyi/results/html/semantics/forms/the-input-element?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=show-picker

show-picker-user-gesture.html is the original test renamed, while show-picker-disabled-readonly.html is the new test, with failures in Chrome and Safari.

**Comment by foolip** [comment]
@josepharhar can you check out the show-picker-disabled-readonly.html tests and see if including that in Interop 2022 would be reasonable?

**Comment by foolip** [comment]
@jgraham @gsnedders could you find the right people to weigh in on this for Gecko and WebKit?

**Comment by josepharhar** [comment]
If we already have/had showPicker tests in interop2022, I don't see anything wrong with including all three of the showPicker tests in the link.
It looks like the new disabled-readonly test was specced here, so I don't think there would be any contention over including it: https://github.com/whatwg/html/pull/7769

**Comment by foolip** [comment]
Thanks @josepharhar!

**Comment by jgraham** [comment]
This seems fine.

**Comment by foolip** [comment]
The two additional tests were labeled in https://github.com/web-platform-tests/wpt-metadata/pull/2813.
