### ISSUE TITLE
Agenda for June 9 meeting

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop-2022#87]
Here's the agenda for our meeting tomorrow:

- https://github.com/web-platform-tests/interop-2022/issues/78 - proposed timeline
- https://github.com/web-platform-tests/interop-2022/issues/82
- https://github.com/web-platform-tests/interop-2022/issues/86
- Test change review:
  - https://github.com/web-platform-tests/interop-2022/issues/81
- Investigation effort updates
  - Editing (@jgraham): https://github.com/web-platform-tests/interop-2022-editing/issues/1#issuecomment-1131993480
  - Pointer and Mouse Events (@flackr): https://github.com/web-platform-tests/interop-2022-pointer/issues/3#issuecomment-1150223304
  - Viewport (@jensimmons): https://github.com/web-platform-tests/interop-2022-viewport/issues/2#issuecomment-1142291728
- Opportunities for celebrating landings? 

Previous meeting: https://github.com/web-platform-tests/interop-2022/issues/85

**Comment by brandonmcconnell** [comment]
Thanks, all. It's worth noting that the CSS `attr()` extended capabilities is not actually a new proposal. Rather, none of the browsers currently support the full spec for the feature.

Spec: https://drafts.csswg.org/css-values-5/Overview.bs#attr-notation

MDN explainer: https://developer.mozilla.org/en-US/docs/Web/CSS/attr

**Comment by jensimmons** [comment]
@brandonmcconnell This group is not the CSS Working Group. We are not writing specifications for technology. We are choosing automated tests of certain already-specified technology to include in the Interop Dashboard.

Proposing that WPT tests for `attr()` be included in Interop 2022 is a new proposal for this group. And right now, we are not adding any new focus areas to Interop 2022. We will start taking proposals for what might get included in Interop 2023 later this year, during the open call period.

**Comment by brandonmcconnell** [comment]
@jensimmons Thanks, Jen! That makes complete sense. I misunderstood.

I only meant to suggest this for Interop 2023. Thanks again!
