### ISSUE TITLE
input type=week/month

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/interop-2022#88]
** Test List **

* /html/dom/reflection-forms.html
* /html/semantics/forms/constraints/form-validation-validity-rangeOverflow.html
* /html/semantics/forms/constraints/form-validation-validity-rangeUnderflow.html
* /html/semantics/forms/constraints/form-validation-validity-valid.html
* /html/semantics/forms/constraints/form-validation-validity-valueMissing.html
* /html/semantics/forms/the-input-element/datetime.html
* /html/semantics/forms/the-input-element/input-stepdown.html
* /html/semantics/forms/the-input-element/input-stepup.html
* /html/semantics/forms/the-input-element/selection.html
* /html/semantics/forms/the-input-element/type-change-state.html
* /html/semantics/forms/the-input-element/valueMode.html

** Rationale **

Per https://github.com/web-platform-tests/interop-2022/issues/11#issuecomment-1043314385 we agreed to exclude these previously, but the tests were never split.

**Comment by foolip** [comment]
@mfreed7 @josepharhar can either of you look into splitting these tests? I know that at least one test was split, but don't know if there's a pending CL/PR for the rest?

**Comment by josepharhar** [comment]
I'll try splitting these

**Comment by josepharhar** [comment]
I split them here: https://chromium-review.googlesource.com/c/chromium/src/+/3721798
I'll post a link to the generated WPT PR which should have test results soon

**Comment by josepharhar** [comment]
Here is the WPT PR for the changes: https://github.com/web-platform-tests/wpt/pull/34560
If nobody objects I'll merge it soon

**Comment by josepharhar** [comment]
I'm going to merge the PR.
The last build of it failed because it couldn't install safari: https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=83434&view=logs&j=bf8f5026-3d1f-5955-26be-17f9e1ef0bb3&t=fb374013-b51a-5838-c2f2-591e11e493ab&l=19
The firefox results look good though, so hopefully I didn't make any mistakes when splitting the tests.

**Comment by foolip** [comment]
Thanks for sorting this out, @josepharhar!
