### ISSUE TITLE
Agenda for July 28 meeting

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/interop-2022#98]
Here's the agenda for our meeting tomorrow:

- FYI: Making meetings weekly (suggested last time, just changed)
- [Interop 2023 RFC](https://github.com/web-platform-tests/rfcs/pull/116) updated, please review
  - Investigation efforts now defined
  - Definition of consensus simplified
  - Renaming repo/team instead of creating new ones 2023
- Interop team charter RFC coming soon (@foolip)
- Test change review:
  - https://github.com/web-platform-tests/interop-2022/issues/97
- Investigation effort updates
  - Editing (@jgraham): https://github.com/web-platform-tests/interop-2022-editing
  - Pointer and Mouse Events (@flackr): https://github.com/web-platform-tests/interop-2022-pointer
  - Viewport (@bramus): https://github.com/web-platform-tests/interop-2022-viewport

Previous meeting: https://github.com/web-platform-tests/interop-2022/issues/95

**Comment by bramus** [comment]
_Attendees: @gsnedders @dlibby- @jgraham @bkardell @bramus_
_Minutes: @bramus_

- Weekly meetings: OK.
- Interop 2023:
  - Rough consensus on renaming the repository as proposed.
  - Few questions though
    - How do we distinguish between interop2022 / interop2023? 
      - Milestones?
      - Labels?
    - Should we close issues?
    - See comment https://github.com/web-platform-tests/rfcs/pull/116/files#r932438734
- Interop team charter RFC coming soon: _(skipped)_
- Test Change Review:
  - People with knowledge about https://github.com/web-platform-tests/interop-2022/issues/97 from each vendor should check before we can move forward on this
    - Folks at Mozilla were pinged.
    - @bramus will ping Chrome team
- Investigation Efforts
  - Editing (@jgraham): 5 areas of interest have been identified and  goals were defined.
  - Pointer and Mouse Events (@flackr): _(skipped)_
  - Viewport (@bramus): Meeting planned for August 10 with attendees from all vendors. A bunch of test-pages have been prepared and will be committed to the repo. Spreadsheet with initial behavioural test results is being built.
